#!/bin/bash
job=$1
working_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
for file in "out log brz gpt esp ump arc syb end"; do
    if [ -e "$job.$file" ]; then mv "$job.$file" "$job.$file.$$"; fi
done
if [ ! -e $job.log ]; then
    touch $job.log
fi
export FOR005=$job.dat
export FOR006=$job.out
export FOR009=$job.res
export FOR010=$job.den
export FOR011=$job.log
export FOR012=$job.arc
export FOR013=$job.gpt
export FOR016=$job.syb
export FOR020=$job.ump
export SETUP=SETUP.DAT
export SHUTDOWN=$job.end
time $working_dir/mopac.exe $job <$job.dat
cat $job.out
if [ -e core ]; then rm core; fi
